spec:
  structures:
    - content_blocks
    - page_blocks
  label: Alternate Grid
  description: Primary content area with list of secondary items
  icon: grid_view
  tags:
    - grid

blueprint:
  image:
  content:
  cta: bookshop:global/cta
  grid_items:
  section:
    transition: curve
    background: primary
  layout:
    image_align: right
    image_width: small

preview:

_inputs:
  grid_items:
    type: array
  grid_items[*]:
    type: object
    options:
      structures: _structures.simple_item
  image:
    type: array
    options:
      structures: _structures.image