spec:
  structures:
    - content_blocks
    - page_blocks
  label: Alternate Grid
  description: Primary content area with list of secondary items
  icon: grid_view
  tags:
    - grid

blueprint:
  content:
  image: bookshop:global/image
  cta: bookshop:global/cta
  grid_items: []
  section:
    transition: curve
    background: primary
  layout:
    image_align: right
    image_vert: center
    image_width: small

preview:

_inputs:
  grid_items:
    type: array
    options:
      empty_type: array
      structures: _structures.simple_item