spec:
  structures:
    - content_blocks
    - page_blocks
  label: Alternate Grid
  description: Primary content area with list of secondary items
  icon: grid_view
  tags:
    - grid

blueprint:
  content:
  cta:
  section:
    transition: curve
    background: primary
  layout:
    image_align: right
    image_width: small

preview:

_inputs: