spec:
  structures:
    - image
    - headshot
  label: Image
  description:
  icon: image
  tags:
    - global
  preview:
    icon: false
    image:
      - key: path
    text:
      - key: path
    subtext:
      - key: alt

blueprint:
  path:
  alt:
  title:
  width:
  height:
  srcset:
  sizes:
  media:

preview:

_inputs:
  path:
    type: image
  alt:
    type: text
  title:
    type: text
  width:
    type: number
  height:
    type: number
  srcset:
    type: text
    comment: 'Use attribute valid value. ex: (max-width: 600px) 480px, 800px'
  sizes:
    type: array
    comment: A list of widths to be exported.
  sizes[*]:
    type: text
  media:
    type: text