spec:
  structures:
    - image
  label: Image
  description:
  icon: image
  tags:
    - global
  preview:
    icon: false
    image:
      - key: src
    text:
      - key: title
      - No image title set
    subtext:
      - key: alt
      - No image alt set

blueprint:
  src:
  alt:
  title:
  width:
  height:
  loading: lazy

preview:

_inputs:
  src:
    type: image
  alt:
    type: text
  title:
    type: text
  width:
    type: number
  height:
    type: number