spec:
  structures:
    - content_blocks
    - page_blocks
  label: Simple Text
  description: Just a simple dispaly of text, no image.
  icon: notes
  tags:
    - text

blueprint:
  eyebrow:
  content:
  cta:
  section:
    transition: curve
    background: primary
  layout:
    text_align: center
    is_mini: true

preview:

_inputs: