spec:
  structures:
    - content_blocks
  label: Form
  description: Content area with form builder
  icon: dynamic_form
  tags:

blueprint:
  content: >-
      <p class="eyebrow">Form</p>


      ### Headline


      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  form: bookshop:form/builder
preview:

_inputs: