spec:
  structures:
    - form_block
  label: Text Field
  description: Input, Textarea
  icon: font_download
  tags:

blueprint:
  label: Text Field
  type: text
  placeholder: Placeholder text
  name:
  required:

preview:

_inputs:
  label:
    type: text
  type:
    select:
      options:
        values:
          - text
          - textarea
          - email
          - tel
          - url
          - date
          - time
          - datetime-local
          - month
          - week
          - color
          - password
  placeholder:
    type: text
  name:
    type: text
    comment: Name of the field - Netlify Forms
  required:
    type: switch