spec:
  structures:
    - grid_item_default
  label: Grid Item
  description: Image and text
  icon: grid_view

blueprint:
  content: >-
      ### Headline with a strong tag


      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  image: bookshop:global/image

preview:

_inputs: