spec:
  structures:
    - content_blocks
  label: Testimonial Cards
  description: Display multiple testimonials in cards
  icon: record_voice_over
  tags:
    - cards

blueprint:
  content: >-
      <p class="eyebrow">Testimonials</p>


      <h2 class="h1">Headline here</h2>


      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non tellus
      sapien. Duis id neque diam. Mauris commodo porta sapien vel viverra. Sed
      finibus.
  testimonials: []
  section:
    transition: curve
    background: primary

preview:

_inputs:
  testimonials:
    type: array
  testimonials[*]:
    type: select
    options:
      value_key: uuid
      values: data.testimonials
      preview:
        text:
          - key: name
        image:
          - key: image