spec:
  structures:
    - content_blocks
    - page_blocks
  label: Testimonial Cards
  description: Display multiple testimonials in cards
  icon: record_voice_over
  tags:
    - cards

blueprint:
  content:
  section:
    transition: curve
    background: primary
  testimonials:

preview:

_inputs: