spec:
  structures:
    - content_blocks
  label: Testimonial Cards
  description: Display multiple testimonials in cards
  icon: record_voice_over
  tags:
    - cards

blueprint:
  content:
  testimonials:
  section:
    transition: curve
    background: primary

preview:

_inputs:
