spec:
  structures:
    - content_blocks
  label: Simple Grid
  description: Primary content area with list of secondary items
  icon: grid_view
  tags:
    - grid

blueprint:
  content: >-
      <p class="eyebrow">Simple Grid</p>


      <h1 class="h1">Headline with a <strong>strong tag</strong></h1>


      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non tellus
      sapien. Duis id neque diam. Mauris commodo porta sapien vel viverra. Sed
      finibus.
  cta: bookshop:global/cta
  grid_items: []
  section:
    transition: curve
    background: primary
  layout:
    text_align: left
    is_mini: true
preview:

_inputs:
  grid_items:
    type: array
    options:
      empty_type: array
      structures: _structures.simple_item