spec:
  structures:
    - content_blocks
    - page_blocks
  label: Simple Grid
  description: Primary content area with list of secondary items
  icon: grid_view
  tags:
    - grid

blueprint:
  content:
  cta: bookshop:global/cta
  section:
    transition: curve
    background: primary
  layout:
    text_align: left
preview:

_inputs: