spec:
  structures:
    - content_blocks
  label: Side By Side
  description: Text and an image
  icon: grid_view
  tags:
    - grid

blueprint:
  content: >-
      <p class="eyebrow">Side by Side</p>


      <h1 class="h1">Headline with a <strong>strong tag</strong></h1>


      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non tellus
      sapien. Duis id neque diam. Mauris commodo porta sapien vel viverra. Sed
      finibus.
  cta: bookshop:global/cta
  image: bookshop:global/image
  section:
    transition: curve
    background: primary
    animation: false
  layout:
    format: left
    content_align: center
    media_align: center
    media_expand: false
    is_mini: false

preview:

_inputs:
  layout.format:
    type: select
    comment: Set the layout
    options:
      allow_empty: false
      values: _select_data.layout_format
  layout.content_align:
    type: select
    options:
      allow_empty: false
      values: _select_data.content_align
  layout.media_align:
    type: select
    options:
      allow_empty: false
      values: _select_data.content_align
  layout.media_expand:
    type: switch
    comment: Grow media cell to fill remaining space.

_select_data:
  layout_format:
    left: Media Left
    right: Media Right
  content_align:
    flex-start: Top
    center: Center
    flex-end: Bottom