spec:
  structures:
    - content_blocks
  label: Side By Side
  description: Text and an image
  icon: grid_view
  tags:
    - grid

blueprint:
  content: >-
      <p class="eyebrow">Side by Side</p>


      <h1 class="h1">Headline with a <strong>strong tag</strong></h1>


      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non tellus
      sapien. Duis id neque diam. Mauris commodo porta sapien vel viverra. Sed
      finibus.
  cta: bookshop:global/cta
  image: bookshop:global/image
  section:
    transition: curve
    background: primary
  layout:
    image_align: right
    image_width: small

preview:

_inputs: