spec:
  structures:
    - content_blocks
    - page_blocks
  label: Post Cards
  description: Display multiple blog and project posts in cards
  icon: article
  tags:
    - cards

blueprint:
  content:
  cards: []
  section:
    transition: curve
    background: primary
  
preview:

_inputs:
  cards:
    type: array
    options:
      empty_type: array
      structures: _structures.collection_card