spec:
  structures:
    - content_blocks
  label: Post Cards
  description: Display multiple blog and project posts in cards
  icon: article
  tags:
    - cards

blueprint:
  content: >-
      <p class="eyebrow">Posts</p>
      <h4 class="h3">Headline here</h4>

  cards: []
  section:
    transition: curve
    background: primary
    animation: false
    
preview:

_inputs:
  cards:
    type: array
    options:
      empty_type: array
      structures: _structures.collection_card