spec:
  structures:
    - content_blocks
    - page_blocks
  label: Post Cards
  description: Display multiple blog and project posts in cards
  icon: article
  tags:
    - cards

blueprint:
  content:
  cards:
  section:
    transition: curve
    background: primary
  
preview:

_inputs:
  cards:
    type: array
    preview:
      text: Card entry
      subtext:
        - key: blog
        - key: project
        - Nothing selected
  cards[*]:
    type: object
  cards[*].blog:
    type: select
    options:
      values: collections.blog
      value_key: uuid
  cards[*].project:
    type: select
    options:
      values: collections.projects
      value_key:
        - path
        - title
        - slug
        - id