spec:
  structures:
    - content_blocks
    - page_blocks
  label: Post Cards
  description: Display multiple blog and project posts in cards
  icon: article
  tags:
    - cards

blueprint:
  content:
  cards:
  section:
    transition: curve
    background: primary
  
preview:

_inputs:
  cards:
    type: array
    options:
      structures: _structures.collection_card
      
_structures:
  collection_card:
    values:
      - label: Project Post
        icon: work
        value:
          _type: project
          project_uuid:
      - label: Blog Post
        icon: wysiwyg
        value:
          _type: blog
          blog_uuid: