spec:
  structures:
    - content_blocks
    - page_blocks
  label: Post Cards
  description: Display multiple blog and project posts in cards
  icon: article
  tags:
    - cards

blueprint:
  content:
  section:
    transition: curve
    background: primary
  posts:

preview:

_inputs:
  posts:
    type: array
  posts[*]:
    type: select
    options:
      values: collections.blog
      value_key: uuid