spec:
  structures:
    - content_blocks
    - page_blocks
  label: Splash Hero
  description: Text area with a support image
  icon: image
  tags:
    - hero

blueprint:
  content: >-
    <p class="eyebrow">Eyebrow</p>


    <h1 class="h1">Headline with a <strong>strong tag</strong></h1>


    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non tellus sapien. Duis id neque diam. Mauris commodo porta sapien vel viverra. Sed finibus.
  image:
    - path:
      alt:
      title:
      width:
      height:
      srcset:
      sizes:
      media: '(min-width: 768px)'
      loading: lazy
    - path:
      alt:
      title:
      width:
      height:
      srcset:
        - 400
        - 600
        - 800
        - 1000
        - 1200
      sizes: 90wv
      media: '(max-width: 767px)'
      loading: lazy
  cta: bookshop:global/cta
  section:
    transition: curve
    background: primary

preview:

_inputs:
  image:
    type: array
    options:
      structures: _structures.image
