spec:
  structures:
    - content_blocks
    - page_blocks
  label: Splash Hero
  description: Text area with a support image
  icon: image
  tags:
    - hero

blueprint:
  eyebrow: null
  content: null
  cta: null
  section: null

preview:

_inputs: