spec:
  structures:
    - content_blocks
    - page_blocks
  label: Splash Hero
  description: Text area with a support image
  icon: image
  tags:
    - hero

blueprint:
  content: >-
    <p class="eyebrow">Eyebrow</p>


    <h1 class="h1">Headline with a <strong>strong tag</strong></h1>


    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non tellus sapien. Duis id neque diam. Mauris commodo porta sapien vel viverra. Sed finibus.
  image:
    - src:
      alt:
      title:
      width:
      height:
      loading: lazy
    - src:
      alt:
      title:
      width:
      height:
      loading: lazy
  cta: bookshop:global/cta
  section:
    transition: curve
    background: primary

preview:

_inputs:
  content:
    type: markdown
    options:
      format: p h1 h2 h3 h4 div
      bold: true
      italic: true
      redo: true
      undo: true
      strike: true
      subscript: true
      superscript: true
      underline: true
      link: true
      styles: /src/styles/cloudcannon_editor.css
  image:
    type: array
    comment: If using two images, first is desktop, secound is mobile.
    options:
      structures: _structures.image
