spec:
  structures:
    - content_blocks
    - page_blocks
  label: Splash Hero
  description: Text area with a support image
  icon: image
  tags:
    - hero

blueprint:
  content:
  image: [bookshop:global/image]
  cta: bookshop:global/cta
  section:
    transition: curve
    background: primary

preview:

_inputs: