spec:
  structures:
    - link
  label: CTA
  description: Call to action button
  icon: ads_click
  tags:
    - global

blueprint:
  label: Click Me
  link:
  style: primary
  new_tab: false

preview:

_inputs: