spec:
  structures:
    - site_link
    - cta
  label: CTA
  description: Call to action button
  icon: smart_button
  tags:
    - global
  preview:
    icon: smart_button
    text:
      - key: label
      - No Label
    subtext:
      - key: link
      - No URL

blueprint:
  label: Click Me
  link:
  style: primary
  new_tab: false

preview:

_inputs:
  label:
    type: text
  link:
    type: url
  new_tab:
    type: checkbox
  style:
    type: select
    options:
      values: _select_data.cta_style