spec:
  structures:
    - content_blocks
  label: FAQs
  description:
  icon: quiz
  tags:

blueprint:
  content:
  faqs: []
  section:
    transition: curve
    background: primary
  layout:
    orintation: left

preview:

_structures:
  faqs:
    values:
      - value:
          question: 
          answer:

_inputs:
  faqs:
    type: array
    label: Questions & Answers
    options:
      structures: _structures.faqs
      empty_type: array
  faqs[*]:
    type: object
  faqs[*].question:
    type: text
  faqs[*].answer:
    type: markdown
    options:
      bold: true
      italic: true
      strike: true
      bulletedlist: true
      numberedlist: true
      undo: true
      redu: true
