spec:
  structures:
    - content_blocks
  label: FAQs
  description:
  icon: quiz
  tags:

blueprint:
  content: >-
    <h4 class="h2">Frequently Asked <strong>Questions</strong></h4>
    
    
    Have a question? I have answered some common questions here. Don't see an answer to your question? [Ask me here](/).
  faqs:
    - question: Donec tempor turpis id egestas vestibulum.
      answer: >-
        *Quisque facilisis, enim non interdum auctor,* felis nibh pellentesque diam, eget dictum massa tellus ut mi.
        Morbi rutrum luctus orci vel interdum. Donec tempor turpis id egestas vestibulum. Pellentesque dictum elit a diam mollis tempus. Etiam tempor fringilla nunc nec egestas.
  section:
    transition: curve
    background: primary
  layout:
    orintation: left

preview:

_inputs:
  faqs:
    type: array
    label: Questions & Answers
    preview:
      icon: quiz
      text:
        - key: question
        - No question set yet
      subtext:
        - key: answer
        - No answer set yet
  faqs[*].question:
    type: text
  faqs[*].answer:
    type: markdown
    options:
      bold: true
      italic: true
      strike: true
      bulletedlist: true
      numberedlist: true
      undo: true
      redu: true
