spec:
  structures:
    - form_block
  label: Select Field
  description: Checkbox, Radio, Combo
  icon: check_box
  tags:

blueprint:
  label:
  type:
  name:
  required:
  options:

preview:

_inputs: