spec:
  structures:
    - site_link
  label: Link
  description: Default link
  icon: link
  preview:
    icon: link
    text:
      - key: label
      - No Label
    subtext:
      - key: link
      - No URL
  tags:
    - global

blueprint:
  label: Click Me
  link:
  new_tab: false

preview:

_inputs:
  label:
    type: text
  link:
    type: url
  new_tab:
    type: checkbox