spec:
  structures:
    - link
  label: Link
  description: Default link
  icon: ads_click
  preview:
    text: Sup Link
    subtext:
      - key: link
      - No URL
  tags:
    - global

blueprint:
  label: Click Me
  link:
  new_tab: false

preview:

_inputs: