spec:
  structures:
    - link
  label: Link
  description: Default link
  icon: ads_click
  preview:
    icon: ads_click
    text:
      - key: label
      - No Label
    subtext:
      - key: link
      - No URL
  tags:
    - global

blueprint:
  label: Click Me
  link:
  new_tab: false

preview:

_inputs:
  label:
    type: text
  link:
    type: url
  new_tab:
    type: checkbox